Repository fungover/breeze, pull requests merged in 2025-02, with the labels that each got.

#56 Javadoc fixes
  src/main/java/org/fungover/breeze/Procrastinator.java
  src/main/java/org/fungover/breeze/funclib/control/Either.java
  src/main/java/org/fungover/breeze/util/Arrays.java
  src/main/java/org/fungover/breeze/util/Strings.java
  src/test/java/org/fungover/breeze/util/ArraysTest.java
Labels: bug, patch

#64 Add a CODEOWNERS file to limit who can approve updates to some files.
  .github/CODEOWNERS
Labels: skip-changelog, pipeline

#51 19 implement zip and zipwith array operations
  src/main/java/org/fungover/breeze/util/Arrays.java
  src/test/java/org/fungover/breeze/util/ArraysTest.java
Labels: minor

#69 #27 Vector Implementation
  src/main/java/org/fungover/breeze/vector/Vector2.java
  src/main/java/org/fungover/breeze/vector/Vector3.java
  src/main/java/org/fungover/breeze/vector/Vector4.java
  src/test/java/org/fungover/breeze/vector/Vector2Test.java
  src/test/java/org/fungover/breeze/vector/Vector3Test.java
  src/test/java/org/fungover/breeze/vector/Vector4Test.java
Labels: feature, minor

#48 Implement Try<T> type for exception handling
  src/main/java/org/fungover/breeze/funclib/control/Try.java
  src/test/java/org/fungover/breeze/funclib/control/TryTest.java
Labels: minor

#67 65 implement tuple2 class
  src/main/java/org/fungover/breeze/control/Tuple2.java
  src/test/java/org/fungover/breeze/control/Tuple2Test.java
Labels: minor

#66 Dijkstra's algorithm
  src/main/java/org/fungover/breeze/graph/Dijkstra.java
  src/main/java/org/fungover/breeze/graph/Edge.java
  src/main/java/org/fungover/breeze/graph/Graph.java
  src/main/java/org/fungover/breeze/graph/Node.java
  src/main/java/org/fungover/breeze/graph/WeightedGraph.java
  src/test/java/org/fungover/breeze/graph/DijkstraTest.java
Labels: minor

#72 18 implement lazyt type for delayed evaluation with memoization
  src/main/java/org/fungover/breeze/control/Lazy.java
  src/test/java/org/fungover/breeze/LazyTest.java
Labels: minor

#60 17-fmultimapk-v-functional-multi-map
  src/main/java/org/fungover/breeze/fmultimap/FMultiMap.java
  src/test/java/org/fungover/breeze/fmultimap/FMultiMapTest.java
Labels: minor

#121 117 implement tuple3 and tuple4 classes
  src/main/java/org/fungover/breeze/control/Tuple3.java
  src/main/java/org/fungover/breeze/control/Tuple4.java
  src/test/java/org/fungover/breeze/control/Tuple3Test.java
  src/test/java/org/fungover/breeze/control/Tuple4Test.java
Labels: minor

#119 52-Implement-Redacted-type
  src/main/java/org/fungover/breeze/util/Redacted.java
  src/main/java/org/fungover/breeze/util/package-info.java
  src/test/java/org/fungover/breeze/util/RedactedTest.java
Labels: feature

#129 13 fsett functional set Add immutable FSet with RedBlackTree and SetProcedural interface
  src/main/java/org/fungover/breeze/collection/FSet.java
  src/main/java/org/fungover/breeze/collection/Node.java
  src/main/java/org/fungover/breeze/collection/RedBlackTree.java
  src/test/java/org/fungover/breeze/collection/FSetTest.java
  src/test/java/org/fungover/breeze/collection/HashCodeWrapperTest.java
  src/test/java/org/fungover/breeze/collection/NodeTest.java
  src/test/java/org/fungover/breeze/collection/RedBlackTreeTest.java
Labels: minor
